def number_to_words(num):
    """Convert number to words (basic implementation for numbers 0-999)"""
    if num == 0:
        return "Zero"
    
    ones = ["", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine"]
    teens = ["Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", 
             "Sixteen", "Seventeen", "Eighteen", "Nineteen"]
    tens = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"]
    
    def convert_below_thousand(n):
        if n == 0:
            return ""
        elif n < 10:
            return ones[n]
        elif n < 20:
            return teens[n - 10]
        elif n < 100:
            return tens[n // 10] + ("" if n % 10 == 0 else " " + ones[n % 10])
        else:
            return ones[n // 100] + " Hundred" + ("" if n % 100 == 0 else " " + convert_below_thousand(n % 100))
    
    if num < 0:
        return "Negative " + number_to_words(-num)
    elif num < 1000:
        return convert_below_thousand(num)
    elif num < 1000000:
        thousands = num // 1000
        remainder = num % 1000
        result = convert_below_thousand(thousands) + " Thousand"
        if remainder > 0:
            result += " " + convert_below_thousand(remainder)
        return result
    else:
        return "Number too large (>999,999)"

def main():
    """Main function to get user input and convert to words"""
    try:
        number = int(input("Enter a number: "))
        words = number_to_words(number)
        print(f"Number: {number}")
        print(f"In words: {words}")
        
        # Since PIL is not available in WebContainer, we'll create an HTML version
        create_html_image(number, words)
        
    except ValueError:
        print("Please enter a valid integer.")
    except Exception as e:
        print(f"An error occurred: {e}")

def create_html_image(number, words):
    """Create an HTML file that displays the text as an image alternative"""
    html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Number {number} in Words</title>
    <style>
        body {{
            margin: 0;
            padding: 0;
            background-color: white;
            font-family: 'Arial', sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }}
        .image-container {{
            background-color: white;
            border: 2px solid #333;
            padding: 40px 60px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
            text-align: center;
            max-width: 80%;
        }}
        .number-display {{
            font-size: 48px;
            font-weight: bold;
            color: #333;
            margin-bottom: 20px;
        }}
        .words-display {{
            font-size: 36px;
            color: #555;
            font-style: italic;
        }}
        .small-text {{
            font-size: 14px;
            color: #888;
            margin-top: 20px;
        }}
    </style>
</head>
<body>
    <div class="image-container">
        <div class="number-display">{number}</div>
        <div class="words-display">{words}</div>
        <div class="small-text">Generated by Number to Words Converter</div>
    </div>
</body>
</html>
"""
    
    filename = f"number_{number}_words.html"
    with open(filename, 'w') as f:
        f.write(html_content)
    
    print(f"\nHTML version created: {filename}")
    print("You can open this file in a browser and take a screenshot for an image version.")

if __name__ == "__main__":
    main()